apiVersion: v1
kind: Service
metadata:
  name: mme
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mme
spec:
  ports:
  - name: mme
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort}}
    nodePort: {{ .Values.nodePort}}
  type: NodePort
  selector:
    app: mme
