---
# tasks file for uninstall-product
 - name: Stopping regal services.
   service:
     name: regal 
     state: stopped

 - name: Un-Installation of Product.
   shell: python /opt/regal/sbin/uninstall-{{prod_name}}-v{{prod_version}}.py


 - name: Starting regal services.
   service:
     name: regal 
     state: started





