apiVersion: v1
kind: Service
metadata:
  name: hss
  namespace: {{ .Values.global.namespace }}
  labels:
    app: hss
spec:
  ports:
  - name: hss
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
    nodePort: {{ .Values.nodePort}}
  - name: hss-rest-api
    port: {{ .Values.servicePort2 }}
    targetPort: {{ .Values.containerPort2 }}
    nodePort: {{ .Values.nodePort2}}
  type: NodePort
  selector:
    app: hss
