---

- hosts: "{{host}}"
  gather_facts: false
  roles:
    - {role: install-iwf, tags: ['install-iwf']}
    - {role: uninstall-iwf, tags: ['uninstall-iwf']}
    - {role: apply-iwf-config, tags: ['apply-iwf-config']}
    - {role: manage-service, tags: ['manage-service']}
    - {role: setup-diameter-stack, tags: ['setup-diameter-stack']}
    - {role: uninstall-diameter-stack, tags: ['uninstall-diameter-stack']}
    - {role: setup-distributed-stack, tags: ['setup-distributed-stack']}
    - {role: setup-distributed-application, tags: ['setup-distributed-application']}
    - {role: uninstall-distributed-stack, tags: ['uninstall-distributed-stack']}
