#  command-line args (--extra-vars switch)
#    rep_path (ex = /stack_apps/IMSDIA-GA-7.5.1-NRD-x86_64.linux-gnu-g%2B%2B.tgz)
#    host (ex=172.16.8.244)
#    src_hostid_script_path (ex = /root/diameter/package/change_host_id)
#    src_licence_file (ex = /root/diameter/package/its.lic)
#    host_id (ex = 00000000)
#
---
   - name: Make sure all the dependencies are installed
      #yum:
      #list: "{{ item }}"
     shell: "rpm -qa | grep {{ item }}"
     register: rpm_list
     with_items:
       - gcc
       - lksctp
       - sed
       - tar
         #- gnutls
       - make

   - set_fact:
      file_name : "{{ rep_path.split('/')[-1] | replace('%2B','+')}}"
   
   - set_fact:
      dir_name : "{{ file_name.rsplit('.', 1)[0] | replace('%2B','+') }}"
   
   - set_fact:
       pack_name: "{{ dir_name.rsplit('.',1)[0] }}"

   - set_fact:
       host_script_name: "{{ src_hostid_script_path.split('/')[-1] }}"

   - name: Creates directory  /opt/Diametriq/ if it doesnt exist
     file:
       path: /opt/Diametriq/
       state: directory

   - set_fact:
      file_path : /opt/Diametriq/{{ file_name }}

   - name: Download package
     copy:
        src: "{{ rep_path }}"
        dest: "{{ file_path }}"
   
   - name: Check {{ file_name }} already exist
     stat: 
       path: "/opt/Diametriq/{{ dir_name }}"
     register: output
        
   - debug:
       msg: "{{ dir_name }}" 

   - name: Untar package {{ file_name }}
     shell: "tar -xf {{ file_name }}"
     args:
       chdir: "/opt/Diametriq/"
     when: not output.stat.exists

   - name: copy host_id change script
     copy:
       src: "{{ src_hostid_script_path }}"
       dest: "/opt/"
     when: file_name is search("DSS") # if DSS in file_name

   - name: change permission
     file:
       path: "/opt/{{ host_script_name }}"
       mode: 0744
     when: file_name is search("DSS") # if DSS in file_name

   - name: Get system hostid
     shell: hostid
     register: sys_host_id
     when: file_name is search("DSS") # if DSS in file_name
    
   - name: Create file and store host_id 
     copy:
       dest: /opt/old_hostid.txt
       content: |
         {{ sys_host_id.stdout }}
     when: file_name is search("DSS") # if DSS in file_name

   - name: Changing hosid of system using script
     shell: "./{{  host_script_name }} {{ host_id }}"
     args:
       chdir: "/opt/"
     when: file_name is search("DSS") # if DSS in file_name
   
   - name: copy licence file
     copy:
       src: "{{ src_licence_file }}"
       dest: "/opt/Diametriq/{{ dir_name }}/config/"
     when: file_name is search("DSS") # if DSS in file_name

   - name: Create file and store package name
     lineinfile:
       dest: /opt/Diametriq/package_distributed_name.txt
       line: "{{ pack_name }}"
       #regexp: '{{ pack_name }}'
       insertafter: EOF
       create: yes

