---
#  command-line args (--extra-vars switch)
#    template_src_path
#    variables to be replaced must be passed

   - set_fact:
      file_name : "{{ template_src_path.split('/')[-1] }}"

   - name: Creates directory  /home/admin if it doesnt exist
     file:
       path: /home/admin
       state: directory

   - set_fact:
      file_path : /home/admin/{{ file_name }}

   - name: copy iwf mysql dump file
     template:
       src: "{{ template_src_path }}"
       dest: "{{ file_path }}"
   
   - name: copy iwf itu xml file
     template:
       src: "{{ iwf_itu_src_path }}"
       dest: /opt/diametriq/iwf/config/
#       owner: root
#       group: root
#       mode: '0644'

       
   - name: Apply Config 
     shell: mysql -uroot -pdiametriq@123 -DDIAMETRIQ < {{ file_path }}

   - name: User Password
     shell: mysql -uroot -pdiametriq@123 -DDIAMETRIQ -se "INSERT INTO UserT (UserName,Password,RoleID) VALUES ('root',cast(0x707d050dd6ad530670254ad3369eca6e as binary),(select ROLE_ID from ROLE_TB where ROLE='admin'))"
                           
 #  - name: Poll for status "IWF status"
 #    shell: "service dre status"
 #    register: status
 #    until: status.stdout is search("6")
 #    retries: 20

