---
#  command-line args (--extra-vars switch)
#    template_src_path
#    variables to be replaced must be passed


   # - name: Start service httpd, if not started
   #   service:
   #    name: iwfmsgstats 
   #    state: started
     - name: iwfmsgstats stats
       shell : /etc/init.d/{{ service }} {{ operation }}


   #   - name: Poll for status "IWF sart"
   #  shell: "service iwfmsgstats start"
   #  register: status
     #until: status.stdout is search("6")
     #retries: 20

