"""
"""
class Constants:
    DOCKER_SERVICE_NAME = "docker"
    UPF_CONATINER_STATUS_CMD = "docker ps -a"
    SMU_CONTAINER_STATUS = "docker ps -a | grep smu"
    FPU_CONTAINER_STATUS = "docker ps -a | grep fpu"
    LBU_CONTAINER_STATUS = "docker ps -a | grep lbu"
    #DPDK_BIND_INTERFACES = "/root/upf/install/script/dpdk-devbind.py -s | grep 'unused=e1000e' | wc  -l"
    DPDK_BIND_INTERFACES = "/root/upf/install/script/dpdk-devbind.py -s "
    DPDK_BIND_SCRIPT = "/root/upf/install/script/dpdk-devbind.py"
    DPDK_BIND_CMD = "/root/upf/install/script/dpdk-devbind.py -b uio_pci_generic"
    K8_SRC_DPDK_DOCKER_FILE = "/opt/regal/product/Telaverge/config/setup_config/docker_dpdk_run_upf.sh"
    SRC_DPDK_DOCKER_FILE = "regal_lib/product/Telaverge/config/setup_config/docker_dpdk_run_upf.sh"
    K8_SRC_SMU_FILE = "/opt/regal/product/Telaverge/config/setup_config/smu_docker.ini"
    SRC_SMU_FILE = "regal_lib/product/Telaverge/config/setup_config/smu_docker.ini"
    DEST_DPDK_DOCKER_FILE = "/root/upf/install/script/docker_dpdk_run_upf.sh"
    DEST_SMU_FILE = "/root/upf/config/smu/smu_docker.ini"
    START_UPF_SCRIPT = "/root/upf/install/script/build_restart_upf.sh"
    BINDED_INTERFACE_PCI_ADDRESS_CMD = \
    "/root/upf/install/script/dpdk-devbind.py -s | grep 'drv=uio_pci_generic' | cut -d ' ' -f 1"
    UNBIND_INTERFACE_CMD= "/root/upf/install/script/dpdk-devbind.py -u "
    BIND_TO_KERNAL_CMD = "/root/upf/install/script/dpdk-devbind.py -b e1000e "
    EXPORT_CMAKE = "export PATH=$PATH:/root/cmake/bin"
    BIND_TO_DRIVER = "drv=uio_pci_generic"
    DEST_SCAPY_FILE_PATH = "/opt/upf/"
    GNODEB_SCAPY_FILE =  "gnb.py"
    SMU_SCAPY_FILE = "smf.py"
    DN_SCAPY_FILE =  "dn.py"
    DEST_SCRIPT_PATH = "/opt/upf"

    UPF_INNER_TRAFFIC_SUBNET_NAME = "internal_traffic"
    UPF_EXTERNAL_TRAFFIC_SUBNET_NAME = "external_traffic"

    UPF_SCRIPT_PATH = "/root/upf/install/script/"
    UPF_SCRIPT = "./docker_clr.sh"